### ISSUE TITLE
fractal demo not working

### ISSUE THREAD

**Issue by pauladam94** [jonasgeiler/lua-fenster#5]
I have just installed this package in luarocks.

I have copy pasted fractal.lua. 

It doesn't work with this error :

```bash
lua: fractal.lua:19: bad argument #3 to 'open' (number expected, got string)
stack traceback:
        [C]: in function 'fenster.open'
        fractal.lua:19: in main chunk
        [C]: in ?
```

**Comment by pauladam94** [comment]
I think the API has change and this example is not at all up to date

**Comment by jonasgeiler** [comment]
Ah yeah, thanks for the heads up!
I did not release a new version since doing a big refactor and updating all the demos. LuaRocks still has an old version on their server that uses a different order of arguments in the fenster.open function (`title, width, height` instead of `width, height, title`).
I'll just release v0.2.0 right now so you can do a `luarocks install fenster` again, downloading the new version and making the demos work again (hopefully), but keep in mind that this project is still a work in progress until v1.0.0.
Thanks for showing interest though!

**Comment by jonasgeiler** [comment]
Alright, so v0.2.0 is out. Let me know if you still have problems running the demos!
Any sort of user feedback is very appreciated at this stage of development!

**Comment by pauladam94** [comment]
Yes of course I know it's a work in progress !
Thanks for the quick feedback.

Now it works just fine ! Very fun to use pacakge !

**Comment by pauladam94** [comment]
Is it possible to contribute to demos ? 
I will do a small game of life demo with fenster if you are interested.

**Comment by jonasgeiler** [comment]
> Is it possible to contribute to demos ? 
> I will do a small game of life demo with fenster if you are interested.

Sounds cool! Give it a shot 😊🔥
